name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build production binary
        run: ./scripts/buildprod.sh

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: notely-474307
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Build and push Docker image to Artifact Registry
        run: |
          gcloud builds submit \
            --tag us-central1-docker.pkg.dev/notely-474307/notely-ar-repo/notely:latest .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/notely-474307/notely-ar-repo/notely:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project notely-474307 \
            --max-instances=4
