name: CD

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: notely-474307
      REGION: us-central1
      REPOSITORY: notely-ar-repo
      IMAGE: notely
      TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build production binary
        run: |
          chmod +x scripts/buildprod.sh
          ./scripts/buildprod.sh

      - name: Setup gcloud (auth with service account)
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Enable required APIs (idempotent)
        run: |
          gcloud services enable artifactregistry.googleapis.com
          gcloud services enable cloudbuild.googleapis.com

      - name: Build & push via Cloud Build
        run: |
          gcloud builds submit \
            --tag "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}" .
